version: '3.7'

services:
  database:
    build:
      context: ./bin/${POSTGRESVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${POSTGRESVERSION}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD-md5}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      POSTGRES_INITDB_WALDIR: ${POSTGRES_INITDB_WALDIR}
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      # <Port exposed> : < POSTGRES Port running inside container>
      - '${HOST_MACHINE_POSTGRES_PORT}:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes: 
      - ${PGDATA-./postgres-data/.data}:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      # - ./scripts/postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    mem_limit: 4g
    cpus: 2
    # user: 1001:1001
    networks: 
      - postgres
    restart: unless-stopped

  pgadmin: 
    depends_on: 
      # This app depend on / linked to service <db>
      - database
    image: dpage/pgadmin4:latest
    container_name: 'pgadmin-${POSTGRESVERSION}'
    ports: 
      - '${PGADMIN_LISTEN_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ${PGADMINDATA-./pgadmin-data/.data}:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge